### ISSUE TITLE
Add more detailed site breakage information

### ISSUE THREAD

**Issue by denschub** [webcompat/knowledge-base#1]
Honza raised a concern that it's sometimes hard to find the URL and STR just based on Bugzilla or WebCompat links. Therefore, it makes sense to add a more detailed way to track breakage. It probably makes sense to bring the `breakage` key to the root level, and add a few fields, something like:

```yaml
breakage:
  - report: https://github.com/webcompat/web-bugs/issues/73604
    url: https://example.com/example
    steps_to_reproduce:
      - click on "foo"
      - click on "bar"
  - report: https://bugzilla.mozilla.org/show_bug.cgi?id=1753874
    url: https://example.net
    steps_to_reproduce:
      - enter "äöü" into the contact form
      - click on "submit"
```
