### ISSUE TITLE
Agree on a `notes` field

### ISSUE THREAD

**Issue by denschub** [webcompat/knowledge-base#37]
I wanted to add some notes in #29, and added a YAML comment above the fields I wanted to explain, like this:

```yaml
# Even though this is affecting Google's sign in process, the issue is only
# users who want to set up 2fa with a hardware token, and the assumption is that
# this is a relatively small subset of users.
severity: high
user_base_impact: small
```

@jgraham suggested adding an explicit notes field in https://github.com/webcompat/knowledge-base/pull/29#discussion_r915907673.

I'm not sure if it's best to have a separate `notes` field for fields, or just a generic field that is an array or strings where we can explain ourselves.
