### ISSUE TITLE
Consider moving console log messages to a separate section

### ISSUE THREAD

**Issue by ksy36** [webcompat/knowledge-base#8]
We could consider adding messages from the console to a separate section. 

Maybe something along the lines of:

```yaml
symptoms:
   description:
      - "Elements on the page are only partially visible or cut out."
      - "Content doesn't fit the screen."
      - "Elements are too big and overflow their parent container."
   console:
     - 'This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.'
```
